package main

import (
	"fmt"
	"log"
	"net/http"
	_ "net/http"

	socketio "github.com/googollee/go-socket.io"
)

func main() {

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	// curl http://localhost:3002/api/v2/
	// indoor/1/4

	// resp, err := http.Get("http://localhost:3002/api/v2/indoor/1/4/power/0")
	// if err != nil {
	// 	// handle err
	// }

	// fmt.Println(resp.Body)
	// defer resp.Body.Close()

	server := socketio.NewServer(nil)

	server.OnConnect("/", func(s socketio.Conn) error {
		s.SetContext("")
		fmt.Println("connected:", s.ID())
		return nil
	})

	server.OnEvent("/", "notice", func(s socketio.Conn, msg string) {
		fmt.Println("notice:", msg)
		s.Emit("reply", "have "+msg)
	})

	server.OnEvent("/chat", "msg", func(s socketio.Conn, msg string) string {
		s.SetContext(msg)
		return "recv " + msg
	})

	server.OnEvent("/", "device/demo123", func(s socketio.Conn, msg string) string {
		s.SetContext(msg)
		fmt.Println("device/demo123", msg)
		return "recv " + msg
	})

	server.OnEvent("/", "bye", func(s socketio.Conn) string {
		last := s.Context().(string)
		s.Emit("bye", last)
		s.Close()
		return last
	})

	server.OnError("/", func(s socketio.Conn, e error) {
		fmt.Println("meet error:", e)
	})

	server.OnDisconnect("/", func(s socketio.Conn, reason string) {
		fmt.Println("closed", reason)
	})

	go server.Serve()
	defer server.Close()

	http.Handle("/socket.io/", server)
	http.Handle("/", http.FileServer(http.Dir("./asset")))
	log.Println("Serving at localhost:8000...")
	log.Fatal(http.ListenAndServe(":8000", nil))
}
